autoClean:
  autoRemove: 180 # 바닥청소 주기를 설정합니다. ( 음수 혹은 0 입력 시 비활성화 )
  maximumEntityByChunk: 10 # 한 청크 당 존재할 수 있는 엔티티의 수를 지정합니다. ( 주민 제외 )
  maximumVillagerByChunk: 20 # 한 청크 당 존재할 수 있는 주민의 수를 지정합니다.
  ableBreedEntity: true # 동물의 번식 가능 여부를 정합니다.
  exceptAutoRemove: # 바닥청소에서 제외 할 아이템의 종류를 지정합니다.
    - COMMAND
  sendRemainMessage: # 바닥청소 예고 메시지 발송 ( 초 단위 )
    - 5 # 5초 남았을 때
    - 10 # 10초 남았을 때
    - 30 # 20초 남았을 때
    - 60 # 60초 남았을 때
  exceptWorld: # 플러그인 적용 제외 월드
    - testWorld
    - dwfgef

# + -------------------------------------------------------------------------------- + #
# | MESSAGE, ERRORMESSAGE SETTINGS ( 메시지 설정 )
# | 유저에게 출력되지 않을 메세지는 해당 라인을 지우시거나
# | 해당 라인의 제일 앞에 '#' 을 붙여 주석으로 처리하시면 됩니다.
# + -------------------------------------------------------------------------------- + #
messages:
  # 접두사
  prefix: " &6최적화 | &r"
  # 바닥청소 완료
  itemRemoved: "&a바닥청소가 완료되었습니다."
  # 바닥청소 경고
  autoRemoveRemain: "&c&l바닥청소까지 %second%초 남았습니다."
  # 청크 언로드 완료
  chunkUnloaded: "&a성공적으로 청크를 언로드하였습니다!"
  # 접속 차단 시 메시지
  kickMessage: "&c관리자에 의해 서버 접속이 차단되었습니다."
  # 접속 차단 활성화 메시지
  joinBlockEnabled: "&a접속 차단이 활성화 되었습니다."
  # 접속 차단 비활성화 메시지
  joinBlockDisabled: "&a접속 차단이 비활성화 되었습니다."
  # 리로드 시 메시지
  reloadCompleted: "&a리로드가 완료되었습니다."
  # 도움말
  helpMessage:
    - "&6=== 도움말 ==="
    - "&6/최적화 리로드 - 플러그인을 리로드합니다."
    - "&6/최적화 바닥청소 - 바닥에 떨어진 아이템을 청소합니다."
    - "&6/최적화 청크언로드 - 플레이어가 없는 청크를 언로드합니다."
    - "&6/최적화 접속토글 - 플레이어 접속 차단을 활성화 / 비활성화 합니다."
errorMessages:
  # 권한 부족
  permissionDenied: "&c권한이 부족합니다!"
